project_id = "dloafvjthatajjdesypr"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600

[functions.google-maps-proxy]
verify_jwt = false