// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dloafvjthatajjdesypr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsb2Fmdmp0aGF0YWpqZGVzeXByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyODc0MDAsImV4cCI6MjA2OTg2MzQwMH0.NYk2x7Rqx1h2VuYeZTcAyESOdd5YGSqjJchpTAIGNJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});